{"name": "verify that user is unable to sign in using invalid Id or invalid Password", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-test='accountNav-signIn']\"}\n  (Session info: chrome=129.0.6668.101); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104c64500 cxxbridge1$str$ptr + 1917112\n1   chromedriver                        0x0000000104c5c890 cxxbridge1$str$ptr + 1885256\n2   chromedriver                        0x000000010486c538 cxxbridge1$string$len + 89424\n3   chromedriver                        0x00000001048b0878 cxxbridge1$string$len + 368784\n4   chromedriver                        0x00000001048eab7c cxxbridge1$string$len + 607124\n5   chromedriver                        0x00000001048a5374 cxxbridge1$string$len + 322444\n6   chromedriver                        0x00000001048a5fc4 cxxbridge1$string$len + 325596\n7   chromedriver                        0x0000000104c2bd2c cxxbridge1$str$ptr + 1685732\n8   chromedriver                        0x0000000104c30530 cxxbridge1$str$ptr + 1704168\n9   chromedriver                        0x0000000104c10e08 cxxbridge1$str$ptr + 1575360\n10  chromedriver                        0x0000000104c30e00 cxxbridge1$str$ptr + 1706424\n11  chromedriver                        0x0000000104c01f94 cxxbridge1$str$ptr + 1514316\n12  chromedriver                        0x0000000104c4d62c cxxbridge1$str$ptr + 1823204\n13  chromedriver                        0x0000000104c4d7ac cxxbridge1$str$ptr + 1823588\n14  chromedriver                        0x0000000104c5c530 cxxbridge1$str$ptr + 1884392\n15  libsystem_pthread.dylib             0x0000000188fb6f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188fb1d34 thread_start + 8\n\n", "trace": "  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_page.py\", line 21, in sign_in_logo\n    context.app.header.click_sign_in_on_main_page()\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/header.py\", line 23, in click_sign_in_on_main_page\n    self.click(*self.CLICK_SIGNIN)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/base_page.py\", line 48, in click\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given open target main page", "status": "passed", "start": 1729191680098, "stop": 1729191684323}, {"name": "When click on sign in logo and click sign in on account page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-test='accountNav-signIn']\"}\n  (Session info: chrome=129.0.6668.101); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104c64500 cxxbridge1$str$ptr + 1917112\n1   chromedriver                        0x0000000104c5c890 cxxbridge1$str$ptr + 1885256\n2   chromedriver                        0x000000010486c538 cxxbridge1$string$len + 89424\n3   chromedriver                        0x00000001048b0878 cxxbridge1$string$len + 368784\n4   chromedriver                        0x00000001048eab7c cxxbridge1$string$len + 607124\n5   chromedriver                        0x00000001048a5374 cxxbridge1$string$len + 322444\n6   chromedriver                        0x00000001048a5fc4 cxxbridge1$string$len + 325596\n7   chromedriver                        0x0000000104c2bd2c cxxbridge1$str$ptr + 1685732\n8   chromedriver                        0x0000000104c30530 cxxbridge1$str$ptr + 1704168\n9   chromedriver                        0x0000000104c10e08 cxxbridge1$str$ptr + 1575360\n10  chromedriver                        0x0000000104c30e00 cxxbridge1$str$ptr + 1706424\n11  chromedriver                        0x0000000104c01f94 cxxbridge1$str$ptr + 1514316\n12  chromedriver                        0x0000000104c4d62c cxxbridge1$str$ptr + 1823204\n13  chromedriver                        0x0000000104c4d7ac cxxbridge1$str$ptr + 1823588\n14  chromedriver                        0x0000000104c5c530 cxxbridge1$str$ptr + 1884392\n15  libsystem_pthread.dylib             0x0000000188fb6f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188fb1d34 thread_start + 8\n\n", "trace": "  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_page.py\", line 21, in sign_in_logo\n    context.app.header.click_sign_in_on_main_page()\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/header.py\", line 23, in click_sign_in_on_main_page\n    self.click(*self.CLICK_SIGNIN)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/base_page.py\", line 48, in click\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1729191684323, "stop": 1729191690346}, {"name": "And click on email chirank57@gmail.com and enter invalid email address", "status": "skipped", "start": 1729191690472, "stop": 1729191690472}, {"name": "And click on password *********** enter invalid password", "status": "skipped", "start": 1729191690472, "stop": 1729191690472}, {"name": "And click on sign in with password", "status": "skipped", "start": 1729191690472, "stop": 1729191690472}, {"name": "Then Verify user can not sign in using invalid email address or password", "status": "skipped", "start": 1729191690472, "stop": 1729191690472}], "start": 1729191678339, "stop": 1729191690472, "uuid": "a1c85ecd-1b67-49ee-ab76-84a1c369576a", "historyId": "f437f88c256f35aaa948a20be39a1838", "fullName": "target main page sign in: verify that user is unable to sign in using invalid Id or invalid Password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "target main page sign in"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}