{"name": "verify that a logged out user can navigate to Sign In page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-test='accountNav-signIn']\"}\n  (Session info: chrome=129.0.6668.101); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001028a4500 cxxbridge1$str$ptr + 1917112\n1   chromedriver                        0x000000010289c890 cxxbridge1$str$ptr + 1885256\n2   chromedriver                        0x00000001024ac538 cxxbridge1$string$len + 89424\n3   chromedriver                        0x00000001024f0878 cxxbridge1$string$len + 368784\n4   chromedriver                        0x000000010252ab7c cxxbridge1$string$len + 607124\n5   chromedriver                        0x00000001024e5374 cxxbridge1$string$len + 322444\n6   chromedriver                        0x00000001024e5fc4 cxxbridge1$string$len + 325596\n7   chromedriver                        0x000000010286bd2c cxxbridge1$str$ptr + 1685732\n8   chromedriver                        0x0000000102870530 cxxbridge1$str$ptr + 1704168\n9   chromedriver                        0x0000000102850e08 cxxbridge1$str$ptr + 1575360\n10  chromedriver                        0x0000000102870e00 cxxbridge1$str$ptr + 1706424\n11  chromedriver                        0x0000000102841f94 cxxbridge1$str$ptr + 1514316\n12  chromedriver                        0x000000010288d62c cxxbridge1$str$ptr + 1823204\n13  chromedriver                        0x000000010288d7ac cxxbridge1$str$ptr + 1823588\n14  chromedriver                        0x000000010289c530 cxxbridge1$str$ptr + 1884392\n15  libsystem_pthread.dylib             0x0000000188fb6f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188fb1d34 thread_start + 8\n\n", "trace": "  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_page.py\", line 21, in sign_in_logo\n    context.app.header.click_sign_in_on_main_page()\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/header.py\", line 23, in click_sign_in_on_main_page\n    self.click(*self.CLICK_SIGNIN)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/base_page.py\", line 48, in click\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given open target main page", "status": "passed", "start": 1729190073351, "stop": 1729190078129}, {"name": "When click on sign in logo and click sign in on account page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-test='accountNav-signIn']\"}\n  (Session info: chrome=129.0.6668.101); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001028a4500 cxxbridge1$str$ptr + 1917112\n1   chromedriver                        0x000000010289c890 cxxbridge1$str$ptr + 1885256\n2   chromedriver                        0x00000001024ac538 cxxbridge1$string$len + 89424\n3   chromedriver                        0x00000001024f0878 cxxbridge1$string$len + 368784\n4   chromedriver                        0x000000010252ab7c cxxbridge1$string$len + 607124\n5   chromedriver                        0x00000001024e5374 cxxbridge1$string$len + 322444\n6   chromedriver                        0x00000001024e5fc4 cxxbridge1$string$len + 325596\n7   chromedriver                        0x000000010286bd2c cxxbridge1$str$ptr + 1685732\n8   chromedriver                        0x0000000102870530 cxxbridge1$str$ptr + 1704168\n9   chromedriver                        0x0000000102850e08 cxxbridge1$str$ptr + 1575360\n10  chromedriver                        0x0000000102870e00 cxxbridge1$str$ptr + 1706424\n11  chromedriver                        0x0000000102841f94 cxxbridge1$str$ptr + 1514316\n12  chromedriver                        0x000000010288d62c cxxbridge1$str$ptr + 1823204\n13  chromedriver                        0x000000010288d7ac cxxbridge1$str$ptr + 1823588\n14  chromedriver                        0x000000010289c530 cxxbridge1$str$ptr + 1884392\n15  libsystem_pthread.dylib             0x0000000188fb6f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188fb1d34 thread_start + 8\n\n", "trace": "  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_page.py\", line 21, in sign_in_logo\n    context.app.header.click_sign_in_on_main_page()\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/header.py\", line 23, in click_sign_in_on_main_page\n    self.click(*self.CLICK_SIGNIN)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/base_page.py\", line 48, in click\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1729190078130, "stop": 1729190085066}, {"name": "Then Verify Sign In form opened", "status": "skipped", "start": 1729190085197, "stop": 1729190085197}], "start": 1729190071340, "stop": 1729190085197, "uuid": "9f847ed3-4140-4743-86c2-ae1f6ab59267", "historyId": "566a925b9af8f3311d9b6e602f842d07", "fullName": "target main page sign in: verify that a logged out user can navigate to Sign In page", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "target main page sign in"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}